## USB port
port: /dev/ttyACM0


##### Calibration ####
### accelerometer
accel_x_min: -228.27
accel_x_max: 221.8
accel_y_min: -231.32
accel_y_max: 241.82
accel_z_min: -226.93
accel_z_max: 221.44

### magnetometer
# standard calibration
magn_x_min: -600.0
magn_x_max: 600.0
magn_y_min: -600.0
magn_y_max: 600.0
magn_z_min: -600.0
magn_z_max: 600.0

# extended calibration
calibration_magn_use_extended: true
magn_ellipsoid_center: [-77.2436, 311.204, -139.858]
magn_ellipsoid_transform: [[0.627363, -0.0470985, 0.0258744], [-0.0470985, 0.960495, -0.0998964], [0.0258744, -0.0998964, 0.680986]]

# AHRS to robot calibration
imu_yaw_calibration: 0.0

### gyroscope
gyro_average_offset_x: 0.1
gyro_average_offset_y: 0.0
gyro_average_offset_z: -0.1
